In [2]:
class MyLr:
    def __init__(self):
        self.m=0
        self.c=0
    def fit(self,x,y):
        n=len(x)
        sum_xy=0
        sum_x_x=0
        for i in range(n):
            sum_xy =sum_xy+x[i]*y[i]
        for i in range(n):
            sum_x_x=sum_x_x+i*i
        denominator=n*sum_x_x-sum(x)*sum(x)
        slope=(n*sum_xy-sum(x)*sum(y))/denominator
        intercept=(sum(y)*sum_x_x-sum(x)*sum_xy)/denominator
        print("slope")
        print(slope)
        print("intercept..")
        print(intercept)
        self.m=slope
        self.c=intercept
    def predict(self,x):
        print(self.m)
        print(self.c)
        y=self.m * x+ self.c
        print("result")
        print(y)
        return y;

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('height.csv')
df

     Height   weight
0      65.0   7.4327
1      65.5   7.5504
2      66.0   7.6673
3      66.5   7.7834
4      67.0   7.8986
..      ...      ...
106   118.0  21.5611
107   118.5  21.7588
108   119.0  21.9568
109   119.5  22.1549
110   120.0  22.3530

[111 rows x 2 columns]

In [5]:
df

     Height   weight
0      65.0   7.4327
1      65.5   7.5504
2      66.0   7.6673
3      66.5   7.7834
4      67.0   7.8986
..      ...      ...
106   118.0  21.5611
107   118.5  21.7588
108   119.0  21.9568
109   119.5  22.1549
110   120.0  22.3530

[111 rows x 2 columns]

In [6]:
x=df['Height'].values

In [7]:
x

array([ 65. ,  65.5,  66. ,  66.5,  67. ,  67.5,  68. ,  68.5,  69. ,
        69.5,  70. ,  70.5,  71. ,  71.5,  72. ,  72.5,  73. ,  73.5,
        74. ,  74.5,  75. ,  75.5,  76. ,  76.5,  77. ,  77.5,  78. ,
        78.5,  79. ,  79.5,  80. ,  80.5,  81. ,  81.5,  82. ,  82.5,
        83. ,  83.5,  84. ,  84.5,  85. ,  85.5,  86. ,  86.5,  87. ,
        87.5,  88. ,  88.5,  89. ,  89.5,  90. ,  90.5,  91. ,  91.5,
        92. ,  92.5,  93. ,  93.5,  94. ,  94.5,  95. ,  95.5,  96. ,
        96.5,  97. ,  97.5,  98. ,  98.5,  99. ,  99.5, 100. , 100.5,
       101. , 101.5, 102. , 102.5, 103. , 103.5, 104. , 104.5, 105. ,
       105.5, 106. , 106.5, 107. , 107.5, 108. , 108.5, 109. , 109.5,
       110. , 110.5, 111. , 111.5, 112. , 112.5, 113. , 113.5, 114. ,
       114.5, 115. , 115.5, 116. , 116.5, 117. , 117.5, 118. , 118.5,
       119. , 119.5, 120. ])

In [8]:
y=df['weight'].values

In [9]:
y

array([ 7.4327,  7.5504,  7.6673,  7.7834,  7.8986,  8.0132,  8.1272,
        8.241 ,  8.3547,  8.468 ,  8.5808,  8.6927,  8.8036,  8.9135,
        9.0221,  9.1292,  9.2347,  9.339 ,  9.442 ,  9.5438,  9.644 ,
        9.7425,  9.8392,  9.9341, 10.0274, 10.1194, 10.2105, 10.3012,
       10.3923, 10.4845, 10.5781, 10.6737, 10.7718, 10.8728, 10.9772,
       11.0851, 11.1966, 11.3114, 11.429 , 11.549 , 11.6707, 11.7937,
       11.9173, 12.0411, 12.1645, 12.2871, 12.4089, 12.5298, 12.6495,
       12.7683, 12.8864, 13.0038, 13.1209, 13.2376, 13.3541, 13.4705,
       13.587 , 13.7041, 13.8217, 13.9403, 14.06  , 14.1811, 14.3037,
       14.4282, 14.5547, 14.6832, 14.814 , 14.9468, 15.0818, 15.2187,
       15.3576, 15.4985, 15.6412, 15.7857, 15.932 , 16.0801, 16.2298,
       16.3812, 16.5342, 16.6889, 16.8454, 17.0036, 17.1637, 17.3256,
       17.4894, 17.655 , 17.8226, 17.9924, 18.1645, 18.339 , 18.5158,
       18.6948, 18.8759, 19.059 , 19.2439, 19.4304, 19.6185, 19.8081,
       19.999 , 20.1912, 20.3846, 20.5789, 20.7741, 20.97  , 21.1666,
       21.3636, 21.5611, 21.7588, 21.9568, 22.1549, 22.353 ])

In [10]:
lr=MyLr()

In [11]:
lr.fit(x,y)

slope
-0.01484219176164415
intercept..
15.322421656871006

In [12]:
result=lr.predict(66.3)

-0.01484219176164415
15.322421656871006
result
14.338384343073999

In [13]:
import pickle

In [15]:
pickle.dump(lr,open('customlr1.pkl',"wb"))